<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HDDT0260" name="Default test" tests="1" failures="1" timestamp="15 Mar 2019 10:19:00 GMT" time="527.933" errors="0">
  <testcase name="feature" time="526.326" classname="DSTPS.Automation.HybridDesktop.PharmacyLookupAutomation.runners.SearchPharmacyLookUpAndVerifySubmittedInformation_TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: The following asserts failed:
	expected [Cust ID^319 - 0319HUMANA1] but found [Cust ID^319 - 0319HUMANA]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: The following asserts failed:
	expected [Cust ID^319 - 0319HUMANA1] but found [Cust ID^319 - 0319HUMANA]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: The following asserts failed:
	expected [Cust ID^319 - 0319HUMANA1] but found [Cust ID^319 - 0319HUMANA]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at DSTPS.Automation.HybridDesktop.PharmacyLookupApp.common.PharmacyLookup_LandingPage_Steps.verifyMemberDetails(PharmacyLookup_LandingPage_Steps.java:103)
	at DSTPS.Automation.HybridDesktop.PharmacyLookupAutomation.stepDefinitions.SearchPharmacyLookUpAndVerifySubmittedInformation.verify_member_details(SearchPharmacyLookUpAndVerifySubmittedInformation.java:57)
	at âœ½.Then Member details should be displayed(features/PharmacyLookup/PharmacyLookup_Search_VerifySubmittedInformation.feature:16)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Default test -->
